### ISSUE TITLE
Find a new name

### ISSUE THREAD

**Issue by michaelcontento** [burningtreeio/desktime#11]
desktime -> https://desktime.com/

**Comment by tinnet** [comment]
Ideas:
* screen addiction
* daily dose of lcd
* stop facing the wall


pictures we can link (find source first and give credit!)

![1395407642611817](https://cloud.githubusercontent.com/assets/67421/14777812/c82797d4-0acf-11e6-9e90-eebfdf8416f8.jpg)
![comics-work-home-bad](https://cloud.githubusercontent.com/assets/67421/14777815/cad5a53e-0acf-11e6-94db-9e2d95195404.jpg)

**Comment by michaelcontento** [comment]
screenRDA 👍

**Comment by michaelcontento** [comment]
#16
